name: Deployando a ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Extrae archivos desde GitHub
      uses: actions/checkout@v3

    - name: Configura credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.MY_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.MY_REGION }}.amazonaws.com/${{ vars.MY_REPOSITORY }}:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster ${{ vars.MY_CLUSTER }} \
          --service ${{ vars.MY_SERVICE }} \
          --force-new-deployment
